default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: oficina_control_development
  username: postgres
  password: postgres
  host: 172.17.0.3
  port: 5432

test:
  <<: *default
  database: oficina_control_test
  username: postgres
  password: postgres
  host: 172.17.0.3
  port: 5432

production:
  <<: *default
  database: oficina_control_production
  username: oficina_control
  password: <%= ENV["OFICINA_CONTROL_DATABASE_PASSWORD"] %>
